---
#Mariadb tasks
- name: Install MariaDB
  become: yes
  yum:
    name: 'mariadb-server'
    state: present
- name: Enable MariaDB (set to autostart)
  become: yes
  service:
    name: 'mariadb'
    enabled: yes
- name: start mariadb
  become: yes
  service:
    name: 'mariadb'
    state: started